image: node:10.15.3
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          deployment: test
          name: Deploy to dev server
          script:
            - npm install
            - npm run deploy
